title: Kappa
description: Musings on Genome Informatics, How World Works and Travel

url: http://bipinnavlakha.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about

social:
   github: bipinnavlakha
   twitter: bipinnavlakha

google_analytics: "UA-58263416-1"
